name: develop pre-merge check

on: 
  push:
    branches:
    - develop
    - test_ci
  pull_request:
    branches:
    - develop
    - test_ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  IMAGE_NODE_VERSION: 14
  GITHUB_ELEMENTS_VERSION: bitcoin-0.21.0
  GITHUB_BITCOIN_VERSION: bitcoin-0.21.0
  GITHUB_DOCKER_IMAGE: docker.pkg.github.com/cryptogarageinc/elements-testing-dockerfile/elements-testing
  ELEMENTS_ENTRYPOINT_PATH: /github/workspace/.github/workflows/docker/test_entrypoint.sh
  BITCOIN_ENTRYPOINT_PATH: /github/workspace/.github/workflows/docker/test_bitcoin_entrypoint.sh

jobs:
  cmake-js-build:
    name: cmake-js build
    timeout-minutes: 50
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-18.04]
        node: [10, 12, 14, 15]
        exclude:
          - os: windows-2019
            node: 10
          - os: macos-10.15
            node: 10
        include:
          - node: 10
            always: false
          - node: 12
            always: false
          - node: 14
            always: false
          - node: 15
            always: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - name: update to npm v7
      if: runner.os == 'Windows'
      run: npm i -g npm@7
    - name: dump node version
      id: node_ver
      run: |
        export node_ver="$(node --version)"
        echo "::set-output name=node_version::$node_ver"
        echo "node_version=$node_ver"
      shell: bash
    - name: node_modules-useCache
      uses: actions/cache@v1
      id: node_cache
      with:
        path: node_modules
        key: node-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
    - name: npm info
      if: steps.node_cache.outputs.cache-hit != 'true'
      id: npm_info
      run: |
        npm --version
        echo "::set-output name=temp_npm_cachedir::$(npm config get cache)"
    - name: use npm cache
      if: runner.os != 'Windows' && steps.node_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      id: npm_cache
      with:
        path: ${{ steps.npm_info.outputs.temp_npm_cachedir }}
        key: npm-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-0
        restore-keys: |
          npm-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-
    - name: npm_install
      if: steps.node_cache.outputs.cache-hit != 'true'
      env:
        CFDJS_UNUSE_ASSET: true
      run: |
        npm set progress=false
        npm ci
    - name: build
      if: steps.node_cache.outputs.cache-hit == 'true' || ${{ matrix.always }} == 'true'
      run: npm run cmake_release_parallel
    - name: test_all
      run: npm run test
    - name: example
      run: npm run example
    - name: elements_example
      run: npm run elements_example
    - name: lint_check
      if: runner.os != 'macOS'
      run: npm run lint_all
    - name: after_job
      run: rm -rf node_modules/cfd-js
      shell: bash
      continue-on-error: true

  bitcoin-e2e-test:
    name: bitcoin e2e test
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image from GitHub Registry
      run: docker pull ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_BITCOIN_VERSION }}
    - name: integration test
      run: |
        docker run -v ${{ github.workspace }}:/github/workspace --entrypoint ${{ env.BITCOIN_ENTRYPOINT_PATH }} ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_BITCOIN_VERSION }}

  elements-e2e-test:
    name: elements e2e test
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image from GitHub Registry
      run: docker pull ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_ELEMENTS_VERSION }}
    - name: integration test
      run: |
        docker run -v ${{ github.workspace }}:/github/workspace --entrypoint ${{ env.ELEMENTS_ENTRYPOINT_PATH }} ${{ env.GITHUB_DOCKER_IMAGE }}:${{ env.GITHUB_ELEMENTS_VERSION }}

  doxygen-ubuntu:
    name: doxygen-ubuntu
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install_doxygen
      run: sudo apt install doxygen graphviz
    - name: doxygen_check
      run: |
        cd doc
        doxygen Doxyfile_quiet_all
