name: develop pre-merge check

on: 
  push:
    branches:
    - develop
    - test_ci
  pull_request:
    branches:
    - develop
    - test_ci

env:
  CMAKE_VERSION: 3.15.5
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  cmake-js-build:
    name: cmake-js build
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [8, 12, 13, 14]
        exclude:
          - os: windows-latest
            node: 8
          - os: macos-latest
            node: 8
          - os: macos-latest
            node: 13
          - os: macos-latest
            node: 14

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.0
      continue-on-error: true
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - name: setup-node retry
      uses: actions/setup-node@v2.1.0
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - name: cmake-useCache-ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v1
      id: cache
      with:
        path: cache/cmake
        key: ${{ runner.os }}-cmake-${{ env.CMAKE_VERSION }}-x64-0
        restore-keys: |
          ${{ runner.os }}-cmake-${{ env.CMAKE_VERSION }}-x64-
    - name: cmake-download-ubuntu
      if: matrix.os == 'ubuntu-latest' && steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p cache/cmake
        cd cache/cmake
        wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
        cd ../..
    - name: cmake-setting-ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        export cmake_file_name="cmake-$CMAKE_VERSION-Linux-x86_64"
        cd cache/cmake
        tar zxvf $cmake_file_name.tar.gz
        chmod +x $cmake_file_name/bin/cmake $cmake_file_name/bin/ctest
        export CURRENT_DIR=$(pwd)
        echo ::add-path::$CURRENT_DIR/$cmake_file_name/bin
        cd ../..
    - name: dump node version
      id: node_ver
      run: |
        export node_ver="$(node --version)"
        echo "::set-output name=node_version::$node_ver"
        echo "node_version=$node_ver"
      shell: bash
    - name: node_modules-useCache
      uses: actions/cache@v1
      id: node_cache
      with:
        path: node_modules
        key: node-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
    - name: npm info
      if: steps.node_cache.outputs.cache-hit != 'true'
      id: npm_info
      run: |
        npm --version
        echo "::set-output name=npm_cachedir::$(npm config get cache)"
    - name: use npm cache
      if: steps.node_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v1
      id: npm_cache
      with:
        path: ${{ steps.npm_info.outputs.npm_cachedir }}
        key: npm-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-0
        restore-keys: |
          npm-${{ runner.os }}-${{ matrix.node }}-${{ steps.node_ver.outputs.node_version }}-
    - name: npm_install
      if: steps.node_cache.outputs.cache-hit != 'true'
      env:
        CFDJS_UNUSE_ASSET: true
      run: |
        npm set progress=false
        npm ci
    - name: build
      if: steps.node_cache.outputs.cache-hit == 'true'
      run: npm run cmake_release_parallel
    - name: test_all
      run: npm run test
    - name: example
      run: npm run example
    - name: elements_example
      run: npm run elements_example
    - name: lint_check
      if: matrix.os != 'macos-latest'
      run: npm run lint_all
    - name: after_job
      run: rm -rf node_modules/cfd-js
      shell: bash
      continue-on-error: true
    - name: ubuntu-after
      if: matrix.os == 'ubuntu-latest'
      run: rm -rf cache/cmake/cmake-$CMAKE_VERSION-Linux-x86_64

  doxygen-ubuntu:
    name: doxygen-ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_doxygen
      run: sudo apt install doxygen graphviz
    - name: doxygen_check
      run: |
        cd doc
        doxygen Doxyfile_quiet_all
