name: code scan

on:
  push:
    branches:
    - master
    - develop
    - features/sprint*
    - feature/code_scanning
    paths:
    - '**.js'
    - '**.ts'
    - '**.cpp'
    - '**.h'
    - '**/code_scanner.yml'
    - '**/external_project_local_setting.config'
  pull_request:
    branches:
    - master
    - develop
    - features/sprint*

jobs:
  analyze-CodeQL:
    name: CodeQL
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: ['cpp', 'javascript']
        # Learn more...
        # https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#overriding-automatic-language-detection

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
        fetch-depth: 2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file. 
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      if: matrix.language == 'javascript'
      uses: github/codeql-action/autobuild@v2
    - name: Manual Build
      if: matrix.language != 'javascript'
      env:
        CFDJS_UNUSE_ASSET: true
      run: |
        npm set progress=false
        npm ci
        npm run cmake_release_parallel

    # ℹ️ Command-line programs to run using the OS shell.
    #  https://git.io/JvXDl

    # ️ If the Autobuild fails above, remove it and uncomment the following three lines and modify them (or add more) to build your code if your project uses a compiled language

    #- run: |
    #   make bootstrap
    #   make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
